theme: minima
title: Alyssa Travitz
github_username: atravitz
email: "alyssatravitz@gmail.com"
linkedin_username: alyssa-travitz-1494957a

minima:

    # linkedin_username: https://www.linkedin.com/in/alyssa-travitz-1494957a/

    # author: Alyssa Travitz


    # header_pages:
    #   research.md
    #   projects.md
    #   outreach.md

