theme: minima
title: Alyssa Travitz
github_username: atravitz
email: "alyssatravitz@gmail.com"

minima:
    # github_username: https://github.com/atravitz
    # linkedin_username: https://www.linkedin.com/in/alyssa-travitz-1494957a/

    # author: Alyssa Travitz


    # header_pages:
    #   research.md
    #   projects.md
    #   outreach.md

